"""Phase 4 — Execute · SwiftPM resource-bundle injection.

SwiftPM emits `<Package>_<Target>.bundle` directories next to the
target's binary in `BuildProductsPath` whenever the target declares
`.process(...)` or `.copy(...)` resources. The autogenerated bundle
accessor (compiled into the target's binary, hence into our framework)
looks them up at runtime via a candidate list whose ObjC variant for
Stripe3DS2 is:

    NSBundle.mainBundle.resourceURL                         -> App.app/
    [NSBundle bundleForClass:[BUNDLER_FINDER class]].resourceURL
                                                            -> <fw>.framework/
    NSBundle.mainBundle.bundleURL                           -> App.app/

Stock SwiftPM relies on the consumer's `Copy Bundle Resources` build
phase to place the .bundle at the App.app root. xcframework-shaped
consumers don't get that build phase — they only see the framework. So
we copy each .bundle into the framework's root (iOS frameworks are
flat, so framework root == `Bundle(for:).resourceURL`). The framework
is then embedded wholesale by the consumer, bringing the bundle
along.

`BUNDLER_FINDER` is statically vendored into every framework that
links the target (e.g. Stripe3DS2's class shows up in StripePayments,
StripeIssuing, etc.). At runtime `[NSBundle bundleForClass:]` resolves
to whichever framework loaded that copy first, so we must place the
bundle in *every* such framework — which is what searching each build
unit's own dd_path naturally produces, since xcodebuild emits the same
bundle alongside the target binary in every archive that links it.
"""
from __future__ import annotations

import shutil
from pathlib import Path
from typing import List, Set

from ..log import dim, verbose_log

from .inject_swiftmodule import _ensure_root_symlink, _framework_content_root


def _find_resource_bundles(dd_path: Path) -> List[Path]:
    """Return every `*.bundle` directory xcodebuild dropped into this slice's
    `BuildProductsPath`. Deduped by basename — the first occurrence wins so
    the canonical ArchiveIntermediates copy is preferred over the symlinked
    `Build/Products` view.
    """
    if not dd_path.is_dir():
        return []
    seen: Set[str] = set()
    found: List[Path] = []
    # Primary: the path xcodebuild's archive action actually populates.
    archive_root = dd_path / "Build" / "Intermediates.noindex" / "ArchiveIntermediates"
    if archive_root.is_dir():
        for path in sorted(archive_root.glob("*/BuildProductsPath/*/*.bundle")):
            if path.is_dir() and path.name not in seen:
                seen.add(path.name)
                found.append(path)
    # Fallback: the `Build/Products/Release-iphone*` symlink view, in case
    # an unusual archive layout (custom xcodeproj build settings) parks
    # bundles there instead of under ArchiveIntermediates.
    products_root = dd_path / "Build" / "Products"
    if products_root.is_dir():
        for path in sorted(products_root.glob("*/*.bundle")):
            if path.is_dir() and path.name not in seen:
                seen.add(path.name)
                found.append(path)
    return found


def inject_resource_bundles(
    *,
    fw_path: Path,
    fw_name: str,
    dd_path: Path,
    variant: str,
    verbose: bool,
) -> int:
    """Copy SwiftPM-emitted resource bundles from this slice's
    `BuildProductsPath` into the framework.

    Idempotent: an existing same-named bundle inside the framework is
    replaced. Returns the number of bundles copied (zero when the target
    declares no `.process` / `.copy` resources, which is the common case).

    Flat (iOS-style) frameworks: bundles drop at the framework root —
    that's where `Bundle(for:).bundleURL` points and where Xcode-built
    iOS frameworks conventionally hold sub-bundles. Versioned
    (macOS-style) frameworks: bundles drop under `Versions/A/Resources/`,
    where Apple puts sub-bundles by convention and where
    `Bundle(for:).resourceURL` looks at runtime. Placing them at the
    framework root on macOS would trip codesigning ("unsealed contents
    present in the root directory of an embedded framework").
    """
    bundles = _find_resource_bundles(dd_path)
    if not bundles:
        return 0
    content_root = _framework_content_root(fw_path)
    if content_root != fw_path:
        dest_dir = content_root / "Resources"
        dest_dir.mkdir(parents=True, exist_ok=True)
    else:
        dest_dir = fw_path
    copied = 0
    for src in bundles:
        dest = dest_dir / src.name
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(src, dest, symlinks=True)
        copied += 1
        verbose_log(verbose, f"  Copied {src.name} into {variant} {fw_name}.framework")
    if copied:
        dim(f"  Injected {copied} SwiftPM resource bundle(s) ({variant})")
        _ensure_root_symlink(fw_path, "Resources")
    return copied
