#!/usr/bin/env python3
"""Concatenate the `spm_to_xcframework` package into a single executable.

The codebase is split into per-phase modules under
`src/spm_to_xcframework/` for development; end users still consume a
single executable script (`/spm-to-xcframework`). This builder stitches
the modules together — in dependency order — into
`src/spm_to_xcframework.py`, then copies that to the repo root as the
executable script with the shebang and chmod +x.

The transformation is deliberately mechanical:

  * Strip relative imports (`from .X import …`, `from ..X import …`) —
    in the single file every name is already in module globals.
  * Strip `from __future__ import annotations` from every module
    except the first (Python only accepts it once, at the top).
  * Strip per-module shebangs and docstrings (the concatenated file
    carries its own banner).
  * Otherwise preserve source text verbatim, including stdlib imports
    (duplicate imports are a no-op).

The sync-check test in the self-test suite compares the on-disk
`/spm-to-xcframework` byte-for-byte against
`src/spm_to_xcframework.py`, so the builder also writes the latter and
copies it across — same artifact, two paths.
"""
from __future__ import annotations

import re
import stat
import sys
from pathlib import Path
from typing import List

HERE = Path(__file__).resolve().parent
PKG_DIR = HERE / "spm_to_xcframework"
SRC = HERE / "spm_to_xcframework.py"
DST = HERE.parent / "spm-to-xcframework"


# Concatenation order. Strict layered DAG: a module here may only
# reference names defined in modules above it (or in stdlib). Mirrors
# the same layering encoded in `spm_to_xcframework/__init__.py`'s
# wildcard-import sequence.
MODULE_ORDER: List[str] = [
    "log.py",
    "errors.py",
    "diagnostics.py",
    "config.py",
    "model.py",
    "platforms.py",
    "fetch.py",
    "inspect.py",
    "plan.py",
    "prepare.py",
    "prune_child.py",
    "execute/archive.py",
    "execute/rename_framework.py",
    "execute/inject_swiftmodule.py",
    "execute/inject_objc.py",
    "execute/inject_clang_system.py",
    "execute/inject_clang_bridge.py",
    "execute/inject_resources.py",
    "execute/create_xcframework.py",
    "execute/dedup.py",
    "execute/run_unit.py",
    "execute/binary_promote.py",
    "output_manifest.py",
    "verify.py",
    "cli.py",
]


PREAMBLE = '''#!/usr/bin/env python3
"""spm-to-xcframework — Build xcframeworks from Swift Package Manager packages.

The pipeline runs in six explicit phases (REWRITE_DESIGN.md §5):

    Fetch  →  Inspect  →  Plan  →  Prepare  →  Execute  →  Verify

Each phase has a single contract. Fetch produces a clean staged copy of the
source (`.git`, `.build`, `.xcodeproj`/`.xcworkspace` siblings, etc. pruned).
Inspect parses `swift package dump-package` once into a typed model. Plan
turns the model + user filters into a list of build units and a whitelist
of `Package.swift` edits. Prepare applies those edits and round-trips the
manifest through `dump-package` again to confirm every requested edit took
effect. Execute runs xcodebuild for each unit (device + simulator slices in
parallel) and merges the slices into xcframeworks. Verify is strict and
per-unit: every output must parse, ship ≥ 2 slices of dynamically-linked
Mach-O, and (for Swift/ObjC/Mixed) carry the relevant ABI surface.

Single-file, stdlib-only, Python 3.9+. No `match` statements, no `tomllib`,
no PEP 604 unions in runtime code (type hints use `from __future__ import
annotations` so they remain strings).

THIS FILE IS AUTO-GENERATED by `src/build_single_file.py` from the
modules under `src/spm_to_xcframework/`. Do not edit it directly —
edit the per-phase modules and re-run the builder.
"""
from __future__ import annotations
'''


TRAILER = '''

if __name__ == "__main__":
    sys.exit(main())
'''


# Relative-import line patterns. Match both single-line and parenthesised
# multi-line forms so we can elide them wholesale.
_RE_REL_IMPORT_START = re.compile(r"^from\s+\.+\w*")
_RE_FUTURE_IMPORT = re.compile(r"^from\s+__future__\s+import\b")


def _strip_leading_docstring(lines: List[str]) -> List[str]:
    """Drop a leading triple-quoted module docstring + any blank lines
    that follow it. Returns the remaining lines.

    Module docstrings repeat the per-phase rationale text, which is
    redundant in the concatenated file (every phase is already
    introduced by a section header banner we insert ourselves).
    """
    i = 0
    # Skip leading blank lines.
    while i < len(lines) and lines[i].strip() == "":
        i += 1
    if i >= len(lines):
        return lines
    first = lines[i].lstrip()
    if first.startswith('"""') or first.startswith("'''"):
        quote = '"""' if first.startswith('"""') else "'''"
        # Single-line docstring?
        if first.count(quote) >= 2:
            i += 1
        else:
            i += 1
            while i < len(lines):
                if quote in lines[i]:
                    i += 1
                    break
                i += 1
    # Skip blank lines after the docstring.
    while i < len(lines) and lines[i].strip() == "":
        i += 1
    return lines[i:]


def _strip_relative_imports(lines: List[str]) -> List[str]:
    """Drop every `from .X import …` and `from ..X import …` line,
    including parenthesised continuations.

    In the concatenated file the names those imports would have
    bound are already module globals — every module's contents share
    a single namespace. Dropping the lines (rather than rewriting
    them) avoids accidental re-binding and keeps the diff against
    the original modules tight.

    Parenthesised continuations are tracked with a depth counter
    (ignoring `()` inside the same-line string literals we recognise)
    so a `)` inside a docstring or string literal embedded in the
    import block doesn't terminate the block early. Our import
    blocks don't carry strings today, but the counter form is the
    same length and removes a maintenance footgun.
    """
    out: List[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.lstrip()
        if _RE_REL_IMPORT_START.match(stripped):
            depth = _paren_delta(line)
            i += 1
            while depth > 0 and i < len(lines):
                depth += _paren_delta(lines[i])
                i += 1
            continue
        out.append(line)
        i += 1
    return out


def _paren_delta(line: str) -> int:
    """Net `(` - `)` count for `line`, ignoring parens inside `"..."`
    and `'...'` string literals (the only string forms relative-import
    lines can carry). Quote-state is reset at every newline since each
    import-block line is parsed independently.
    """
    depth = 0
    quote: str = ""
    i = 0
    while i < len(line):
        ch = line[i]
        if quote:
            if ch == "\\":
                i += 2
                continue
            if ch == quote:
                quote = ""
            i += 1
            continue
        if ch in ("'", '"'):
            quote = ch
        elif ch == "#":
            break  # rest of line is a comment
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        i += 1
    return depth


def _strip_future_imports(lines: List[str]) -> List[str]:
    """Drop every `from __future__ import …` line. The preamble owns
    the single permitted occurrence."""
    return [l for l in lines if not _RE_FUTURE_IMPORT.match(l.lstrip())]


def _strip_leading_shebang(lines: List[str]) -> List[str]:
    """Drop a leading `#!` line if present. Only the preamble keeps
    its shebang; per-module shebangs would otherwise become stray
    comments inside the concatenated file."""
    if lines and lines[0].startswith("#!"):
        return lines[1:]
    return lines


def _process_module(path: Path) -> str:
    text = path.read_text()
    lines = text.splitlines(keepends=True)
    lines = _strip_leading_shebang(lines)
    lines = _strip_leading_docstring(lines)
    lines = _strip_future_imports(lines)
    lines = _strip_relative_imports(lines)
    return "".join(lines)


def _section_banner(module_rel: str) -> str:
    return (
        "\n\n"
        "# " + "=" * 76 + "\n"
        f"# --- {module_rel} " + ("-" * (max(0, 70 - len(module_rel)))) + "\n"
        "# " + "=" * 76 + "\n\n"
    )


def main() -> int:
    if not PKG_DIR.is_dir():
        print(f"package directory missing: {PKG_DIR}", file=sys.stderr)
        return 1
    parts: List[str] = [PREAMBLE]
    for rel in MODULE_ORDER:
        module_path = PKG_DIR / rel
        if not module_path.is_file():
            print(f"missing module: {module_path}", file=sys.stderr)
            return 1
        parts.append(_section_banner(rel))
        parts.append(_process_module(module_path))
    parts.append(TRAILER)
    output = "".join(parts)

    SRC.write_text(output)
    DST.write_text(output)
    mode = DST.stat().st_mode
    DST.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"Wrote {SRC} ({len(output)} bytes)")
    print(f"Wrote {DST} ({len(output)} bytes, +x)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
